# Generated by Django 5.1.4 on 2025-01-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydocument',
            name='file',
            field=models.FileField(default=1, upload_to='study_documents/'),
            preserve_default=False,
        ),
    ]
