# Generated by Django 5.1.4 on 2025-01-31 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeprofile',
            name='budget',
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier_profile_object_id', models.PositiveIntegerField()),
                ('multiplier_obj_object_id', models.PositiveIntegerField()),
                ('multiplier', models.FloatField(default=0.0)),
                ('multiplier_obj_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplier_objects', to='contenttypes.contenttype')),
                ('multiplier_profile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplier_profiles', to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='hq.userprofile')),
            ],
        ),
    ]
