# Generated by Django 5.1.4 on 2025-01-31 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0001_initial'),
        ('hq', '0002_remove_financeprofile_budget_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLifeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homelife_profiles', to='homelife.household')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homelife_profile', to='hq.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homelife_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
