# Generated by Django 5.1.4 on 2025-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0003_homelifeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplier',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
