# Generated by Django 5.1.4 on 2025-02-14 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0004_alter_multiplier_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profiles', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='homelifeprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homelife_profiles', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_profiles', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_profiles', to='hq.userprofile'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='hq.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('SCHOOL', 'School'), ('WORK', 'Work'), ('HOMELIFE', 'HomeLife'), ('FINANCE', 'Finance')], max_length=20)),
                ('experience_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_experiences', to='hq.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'module_type')},
            },
        ),
        migrations.CreateModel(
            name='ModulePopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('SCHOOL', 'School'), ('WORK', 'Work'), ('HOMELIFE', 'HomeLife'), ('FINANCE', 'Finance')], max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_populations', to='hq.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'module_type')},
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('SCHOOL', 'School'), ('WORK', 'Work'), ('HOMELIFE', 'HomeLife'), ('FINANCE', 'Finance')], max_length=20)),
                ('streak_start', models.DateTimeField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('building_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_statuses', to='hq.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'module_type')},
            },
        ),
    ]
