# Generated by Django 5.1.4 on 2025-02-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0005_alter_financeprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleexperience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modulepopulation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modulestatus',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='financeprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='homelifeprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homelife_profile', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='modulestatus',
            name='building_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modulestatus',
            name='streak_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='hq.userprofile'),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_profile', to='hq.userprofile'),
        ),
    ]
