# Generated by Django 5.1.4 on 2025-02-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0007_moduletask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduletask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moduletask',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='module_tasks', to='hq.userprofile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='moduletask',
            name='user',
        ),
    ]
