# Generated by Django 5.1.4 on 2025-02-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_alter_moduletask_unique_together_moduletask_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduletask',
            unique_together={('profile', 'date', 'module', 'task_number')},
        ),
    ]
