# Generated by Django 5.1.4 on 2025-02-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_calendarevent'),
        ('hq', '0009_alter_moduletask_unique_together'),
    ]

    operations = [
    ]
