# Generated by Django 5.1.4 on 2025-04-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0002_remove_chore_due_date_remove_household_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chorecompletion',
            old_name='profile',
            new_name='homelife_profile',
        ),
    ]
