# Generated by Django 5.1.4 on 2025-04-15 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0003_rename_profile_chorecompletion_homelife_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='household',
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='homelife.household')),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
            },
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='grocery_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='homelife.grocerylist'),
            preserve_default=False,
        ),
    ]
