# Generated by Django 5.1.4 on 2025-04-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0004_remove_groceryitem_household_grocerylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='child_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_child_chores', to='homelife.childprofile'),
        ),
    ]
