# Generated by Django 5.1.4 on 2025-04-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('homelife', '0005_chore_child_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['run_datetime', 'created_at']},
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='run_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='care_frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('MORNINGANDNIGHT', 'Morning and Night'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=16),
        ),
        migrations.AddField(
            model_name='pet',
            name='care_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedcalendarevent',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sharedcalendarevent',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='sharedcalendarevent',
            index=models.Index(fields=['household', 'start_datetime'], name='homelife_sh_househo_7884c3_idx'),
        ),
    ]
