# Generated by Django 5.1.4 on 2025-04-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelife', '0006_alter_grocerylist_options_grocerylist_run_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='medications',
            new_name='medication_instructions',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='care_frequency',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='care_time',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='pet',
            name='food_frequency',
            field=models.CharField(blank=True, choices=[('', '—'), ('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pet',
            name='food_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_frequency',
            field=models.CharField(blank=True, choices=[('', '—'), ('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pet',
            name='water_frequency',
            field=models.CharField(blank=True, choices=[('', '—'), ('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pet',
            name='water_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
