# Generated by Django 5.1.4 on 2025-01-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_transaction_bank_account_remove_bill_user_and_more'),
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoportfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_portfolios', to='hq.financeprofile'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolios', to='hq.financeprofile'),
        ),
    ]
