# Generated by Django 5.1.4 on 2025-04-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_cryptoportfolio_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='profile',
            new_name='finance_profile',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='profile',
            new_name='finance_profile',
        ),
        migrations.RenameField(
            model_name='stockportfolio',
            old_name='profile',
            new_name='finance_profile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='profile',
            new_name='finance_profile',
        ),
    ]
