# Generated by Django 5.1.4 on 2025-04-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_rename_profile_bankaccount_finance_profile_and_more'),
        ('hq', '0012_alter_financeprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='finance_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_portfolio', serialize=False, to='hq.financeprofile'),
        ),
    ]
