# Generated by Django 5.1.4 on 2025-04-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_stockportfolio_id_and_more'),
        ('hq', '0012_alter_financeprofile_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='finance_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='hq.financeprofile'),
        ),
    ]
