# Generated by Django 5.1.4 on 2025-01-31 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hq', '0002_remove_financeprofile_budget_multiplier'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_senders', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FINANCE', 'Finance'), ('HOMELIFE', 'Homelife'), ('WORK', 'Work'), ('SCHOOL', 'School'), ('PROFILE', 'Profile'), ('CALENDAR', 'Calendar')], default='PROFILE', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hq.userprofile'),
        ),
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease'), ('DUE', 'Due'), ('COMING_UP', 'Coming Up'), ('IS_LATE', 'Is Late'), ('CHECK_ON', 'Check On'), ('CHECK_OUT', 'Check Out'), ('DO_NOTHING', 'Do Nothing')], default='DO_NOTHING', max_length=50)),
                ('action_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='notifications.notification')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
