# Generated by Django 5.1.4 on 2025-01-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('work', '0002_remove_meetingnote_meeting_remove_project_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
