# Generated by Django 5.1.4 on 2025-01-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_financeprofile_workprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
