# Generated by Django 5.1.4 on 2025-01-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_financeprofile_user_and_more'),
        ('finances', '0003_alter_cryptoportfolio_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceProfile',
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
